# Changes here will be overwritten by Copier
_commit: v0.5.0
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2026'
email: vdj@vdjserver.org
existing_license_file: ''
full_name: Tanzira Najnin
gh_action_docs_preview: true
gh_action_pypi: true
github_org: vdjserver
license: GPL-3.0-only
project_description: LinkML representation of AIRR Standard schema for VDJServer data
    modeling and database generation.
project_name: vdjserver-airr-schema
project_slug: vdjserver_airr_schema

