---
site_name: "vdjserver-airr-schema"
theme:
  # https://www.mkdocs.org/user-guide/configuration/#theme
  name: material
  icon:
    logo: material/book-open-page-variant
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
    - header.autohide      # maximum screen space during scrolling
    - navigation.expand    # optimize user experience
    - navigation.instant   # optimize user experience
    - navigation.instant.progress
    - navigation.tracking  # update address bar
    - search.suggest       # suggest good completions
    - content.code.copy    # enable copy to clipboard

# extra css/js see https://www.mkdocs.org/user-guide/customizing-your-theme/
extra_css: []
extra_javascript: []

plugins:
  - search
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 11.4.1
  # https://pypi.org/project/mkdocs-pymdownx-material-extras
  - mkdocs_pymdownx_material_extras:

markdown_extensions:
  - pymdownx.superfences:
      # https://mkdocs-mermaid2.readthedocs.io/en/latest/superfences
      # custom code highlighting rules
      custom_fences:
        - name: mermaid
          # disable code highlighting to display diagrams
          format: !!python/name:pymdownx.superfences.fence_code_format
          class: mermaid
  # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  # auto-link HTML, FTP, and email links
  - pymdownx.magiclink
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition
  # support for call-outs
  - admonition
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#tables
  # create tables
  - tables
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
  # enables use of HTML attributes and CSS classes to applicable elements
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
  # write markdown inside of HTML
  - md_in_html

watch:
  - src/vdjserver_airr_schema/schema

nav:
  - Home: index.md
  - Schema: elements/index.md
  - About: about.md

exclude_docs: |
  /templates-linkml/

site_url: https://vdjserver.github.io/vdjserver-airr-schema
repo_url: https://github.com/vdjserver/vdjserver-airr-schema

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
